// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Message_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Message_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Message_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Message_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Message_2eproto;
namespace com {
namespace chuzi {
namespace imsdk {
namespace server {
namespace model {
namespace proto {
class Message;
struct MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace proto
}  // namespace model
}  // namespace server
}  // namespace imsdk
}  // namespace chuzi
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> ::com::chuzi::imsdk::server::model::proto::Message* Arena::CreateMaybeMessage<::com::chuzi::imsdk::server::model::proto::Message>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace com {
namespace chuzi {
namespace imsdk {
namespace server {
namespace model {
namespace proto {

// ===================================================================

class Message final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:com.chuzi.imsdk.server.model.proto.Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  ~Message() override;
  explicit PROTOBUF_CONSTEXPR Message(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Message& default_instance() {
    return *internal_default_instance();
  }
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Message& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Message& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "com.chuzi.imsdk.server.model.proto.Message";
  }
  protected:
  explicit Message(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kContentFieldNumber = 3,
    kSenderFieldNumber = 4,
    kReceiverFieldNumber = 5,
    kExtraFieldNumber = 6,
    kTitleFieldNumber = 7,
    kReadUIdsFieldNumber = 11,
    kSceneFieldNumber = 2,
    kTypeFieldNumber = 8,
    kTimestampFieldNumber = 10,
    kSubTypeFieldNumber = 9,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string content = 3;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // string sender = 4;
  void clear_sender();
  const std::string& sender() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender();
  PROTOBUF_NODISCARD std::string* release_sender();
  void set_allocated_sender(std::string* sender);
  private:
  const std::string& _internal_sender() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender(const std::string& value);
  std::string* _internal_mutable_sender();
  public:

  // string receiver = 5;
  void clear_receiver();
  const std::string& receiver() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_receiver(ArgT0&& arg0, ArgT... args);
  std::string* mutable_receiver();
  PROTOBUF_NODISCARD std::string* release_receiver();
  void set_allocated_receiver(std::string* receiver);
  private:
  const std::string& _internal_receiver() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_receiver(const std::string& value);
  std::string* _internal_mutable_receiver();
  public:

  // string extra = 6;
  void clear_extra();
  const std::string& extra() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_extra(ArgT0&& arg0, ArgT... args);
  std::string* mutable_extra();
  PROTOBUF_NODISCARD std::string* release_extra();
  void set_allocated_extra(std::string* extra);
  private:
  const std::string& _internal_extra() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_extra(const std::string& value);
  std::string* _internal_mutable_extra();
  public:

  // string title = 7;
  void clear_title();
  const std::string& title() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_title(ArgT0&& arg0, ArgT... args);
  std::string* mutable_title();
  PROTOBUF_NODISCARD std::string* release_title();
  void set_allocated_title(std::string* title);
  private:
  const std::string& _internal_title() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_title(const std::string& value);
  std::string* _internal_mutable_title();
  public:

  // string readUIds = 11;
  void clear_readuids();
  const std::string& readuids() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_readuids(ArgT0&& arg0, ArgT... args);
  std::string* mutable_readuids();
  PROTOBUF_NODISCARD std::string* release_readuids();
  void set_allocated_readuids(std::string* readuids);
  private:
  const std::string& _internal_readuids() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_readuids(const std::string& value);
  std::string* _internal_mutable_readuids();
  public:

  // int32 scene = 2;
  void clear_scene();
  int32_t scene() const;
  void set_scene(int32_t value);
  private:
  int32_t _internal_scene() const;
  void _internal_set_scene(int32_t value);
  public:

  // int32 type = 8;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // int64 timestamp = 10;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // int32 subType = 9;
  void clear_subtype();
  int32_t subtype() const;
  void set_subtype(int32_t value);
  private:
  int32_t _internal_subtype() const;
  void _internal_set_subtype(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:com.chuzi.imsdk.server.model.proto.Message)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr receiver_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr extra_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr title_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr readuids_;
  int32_t scene_;
  int32_t type_;
  int64_t timestamp_;
  int32_t subtype_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Message_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Message

// string id = 1;
inline void Message::clear_id() {
  id_.ClearToEmpty();
}
inline const std::string& Message::id() const {
  // @@protoc_insertion_point(field_get:com.chuzi.imsdk.server.model.proto.Message.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_id(ArgT0&& arg0, ArgT... args) {
 
 id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:com.chuzi.imsdk.server.model.proto.Message.id)
}
inline std::string* Message::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:com.chuzi.imsdk.server.model.proto.Message.id)
  return _s;
}
inline const std::string& Message::_internal_id() const {
  return id_.Get();
}
inline void Message::_internal_set_id(const std::string& value) {
  
  id_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_id() {
  
  return id_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_id() {
  // @@protoc_insertion_point(field_release:com.chuzi.imsdk.server.model.proto.Message.id)
  return id_.Release();
}
inline void Message::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (id_.IsDefault()) {
    id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.chuzi.imsdk.server.model.proto.Message.id)
}

// int32 scene = 2;
inline void Message::clear_scene() {
  scene_ = 0;
}
inline int32_t Message::_internal_scene() const {
  return scene_;
}
inline int32_t Message::scene() const {
  // @@protoc_insertion_point(field_get:com.chuzi.imsdk.server.model.proto.Message.scene)
  return _internal_scene();
}
inline void Message::_internal_set_scene(int32_t value) {
  
  scene_ = value;
}
inline void Message::set_scene(int32_t value) {
  _internal_set_scene(value);
  // @@protoc_insertion_point(field_set:com.chuzi.imsdk.server.model.proto.Message.scene)
}

// string content = 3;
inline void Message::clear_content() {
  content_.ClearToEmpty();
}
inline const std::string& Message::content() const {
  // @@protoc_insertion_point(field_get:com.chuzi.imsdk.server.model.proto.Message.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_content(ArgT0&& arg0, ArgT... args) {
 
 content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:com.chuzi.imsdk.server.model.proto.Message.content)
}
inline std::string* Message::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:com.chuzi.imsdk.server.model.proto.Message.content)
  return _s;
}
inline const std::string& Message::_internal_content() const {
  return content_.Get();
}
inline void Message::_internal_set_content(const std::string& value) {
  
  content_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_content() {
  
  return content_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_content() {
  // @@protoc_insertion_point(field_release:com.chuzi.imsdk.server.model.proto.Message.content)
  return content_.Release();
}
inline void Message::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (content_.IsDefault()) {
    content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.chuzi.imsdk.server.model.proto.Message.content)
}

// string sender = 4;
inline void Message::clear_sender() {
  sender_.ClearToEmpty();
}
inline const std::string& Message::sender() const {
  // @@protoc_insertion_point(field_get:com.chuzi.imsdk.server.model.proto.Message.sender)
  return _internal_sender();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_sender(ArgT0&& arg0, ArgT... args) {
 
 sender_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:com.chuzi.imsdk.server.model.proto.Message.sender)
}
inline std::string* Message::mutable_sender() {
  std::string* _s = _internal_mutable_sender();
  // @@protoc_insertion_point(field_mutable:com.chuzi.imsdk.server.model.proto.Message.sender)
  return _s;
}
inline const std::string& Message::_internal_sender() const {
  return sender_.Get();
}
inline void Message::_internal_set_sender(const std::string& value) {
  
  sender_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_sender() {
  
  return sender_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_sender() {
  // @@protoc_insertion_point(field_release:com.chuzi.imsdk.server.model.proto.Message.sender)
  return sender_.Release();
}
inline void Message::set_allocated_sender(std::string* sender) {
  if (sender != nullptr) {
    
  } else {
    
  }
  sender_.SetAllocated(sender, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sender_.IsDefault()) {
    sender_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.chuzi.imsdk.server.model.proto.Message.sender)
}

// string receiver = 5;
inline void Message::clear_receiver() {
  receiver_.ClearToEmpty();
}
inline const std::string& Message::receiver() const {
  // @@protoc_insertion_point(field_get:com.chuzi.imsdk.server.model.proto.Message.receiver)
  return _internal_receiver();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_receiver(ArgT0&& arg0, ArgT... args) {
 
 receiver_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:com.chuzi.imsdk.server.model.proto.Message.receiver)
}
inline std::string* Message::mutable_receiver() {
  std::string* _s = _internal_mutable_receiver();
  // @@protoc_insertion_point(field_mutable:com.chuzi.imsdk.server.model.proto.Message.receiver)
  return _s;
}
inline const std::string& Message::_internal_receiver() const {
  return receiver_.Get();
}
inline void Message::_internal_set_receiver(const std::string& value) {
  
  receiver_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_receiver() {
  
  return receiver_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_receiver() {
  // @@protoc_insertion_point(field_release:com.chuzi.imsdk.server.model.proto.Message.receiver)
  return receiver_.Release();
}
inline void Message::set_allocated_receiver(std::string* receiver) {
  if (receiver != nullptr) {
    
  } else {
    
  }
  receiver_.SetAllocated(receiver, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (receiver_.IsDefault()) {
    receiver_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.chuzi.imsdk.server.model.proto.Message.receiver)
}

// string extra = 6;
inline void Message::clear_extra() {
  extra_.ClearToEmpty();
}
inline const std::string& Message::extra() const {
  // @@protoc_insertion_point(field_get:com.chuzi.imsdk.server.model.proto.Message.extra)
  return _internal_extra();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_extra(ArgT0&& arg0, ArgT... args) {
 
 extra_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:com.chuzi.imsdk.server.model.proto.Message.extra)
}
inline std::string* Message::mutable_extra() {
  std::string* _s = _internal_mutable_extra();
  // @@protoc_insertion_point(field_mutable:com.chuzi.imsdk.server.model.proto.Message.extra)
  return _s;
}
inline const std::string& Message::_internal_extra() const {
  return extra_.Get();
}
inline void Message::_internal_set_extra(const std::string& value) {
  
  extra_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_extra() {
  
  return extra_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_extra() {
  // @@protoc_insertion_point(field_release:com.chuzi.imsdk.server.model.proto.Message.extra)
  return extra_.Release();
}
inline void Message::set_allocated_extra(std::string* extra) {
  if (extra != nullptr) {
    
  } else {
    
  }
  extra_.SetAllocated(extra, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (extra_.IsDefault()) {
    extra_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.chuzi.imsdk.server.model.proto.Message.extra)
}

// string title = 7;
inline void Message::clear_title() {
  title_.ClearToEmpty();
}
inline const std::string& Message::title() const {
  // @@protoc_insertion_point(field_get:com.chuzi.imsdk.server.model.proto.Message.title)
  return _internal_title();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_title(ArgT0&& arg0, ArgT... args) {
 
 title_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:com.chuzi.imsdk.server.model.proto.Message.title)
}
inline std::string* Message::mutable_title() {
  std::string* _s = _internal_mutable_title();
  // @@protoc_insertion_point(field_mutable:com.chuzi.imsdk.server.model.proto.Message.title)
  return _s;
}
inline const std::string& Message::_internal_title() const {
  return title_.Get();
}
inline void Message::_internal_set_title(const std::string& value) {
  
  title_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_title() {
  
  return title_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_title() {
  // @@protoc_insertion_point(field_release:com.chuzi.imsdk.server.model.proto.Message.title)
  return title_.Release();
}
inline void Message::set_allocated_title(std::string* title) {
  if (title != nullptr) {
    
  } else {
    
  }
  title_.SetAllocated(title, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (title_.IsDefault()) {
    title_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.chuzi.imsdk.server.model.proto.Message.title)
}

// int32 type = 8;
inline void Message::clear_type() {
  type_ = 0;
}
inline int32_t Message::_internal_type() const {
  return type_;
}
inline int32_t Message::type() const {
  // @@protoc_insertion_point(field_get:com.chuzi.imsdk.server.model.proto.Message.type)
  return _internal_type();
}
inline void Message::_internal_set_type(int32_t value) {
  
  type_ = value;
}
inline void Message::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:com.chuzi.imsdk.server.model.proto.Message.type)
}

// int32 subType = 9;
inline void Message::clear_subtype() {
  subtype_ = 0;
}
inline int32_t Message::_internal_subtype() const {
  return subtype_;
}
inline int32_t Message::subtype() const {
  // @@protoc_insertion_point(field_get:com.chuzi.imsdk.server.model.proto.Message.subType)
  return _internal_subtype();
}
inline void Message::_internal_set_subtype(int32_t value) {
  
  subtype_ = value;
}
inline void Message::set_subtype(int32_t value) {
  _internal_set_subtype(value);
  // @@protoc_insertion_point(field_set:com.chuzi.imsdk.server.model.proto.Message.subType)
}

// int64 timestamp = 10;
inline void Message::clear_timestamp() {
  timestamp_ = int64_t{0};
}
inline int64_t Message::_internal_timestamp() const {
  return timestamp_;
}
inline int64_t Message::timestamp() const {
  // @@protoc_insertion_point(field_get:com.chuzi.imsdk.server.model.proto.Message.timestamp)
  return _internal_timestamp();
}
inline void Message::_internal_set_timestamp(int64_t value) {
  
  timestamp_ = value;
}
inline void Message::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:com.chuzi.imsdk.server.model.proto.Message.timestamp)
}

// string readUIds = 11;
inline void Message::clear_readuids() {
  readuids_.ClearToEmpty();
}
inline const std::string& Message::readuids() const {
  // @@protoc_insertion_point(field_get:com.chuzi.imsdk.server.model.proto.Message.readUIds)
  return _internal_readuids();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Message::set_readuids(ArgT0&& arg0, ArgT... args) {
 
 readuids_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:com.chuzi.imsdk.server.model.proto.Message.readUIds)
}
inline std::string* Message::mutable_readuids() {
  std::string* _s = _internal_mutable_readuids();
  // @@protoc_insertion_point(field_mutable:com.chuzi.imsdk.server.model.proto.Message.readUIds)
  return _s;
}
inline const std::string& Message::_internal_readuids() const {
  return readuids_.Get();
}
inline void Message::_internal_set_readuids(const std::string& value) {
  
  readuids_.Set(value, GetArenaForAllocation());
}
inline std::string* Message::_internal_mutable_readuids() {
  
  return readuids_.Mutable(GetArenaForAllocation());
}
inline std::string* Message::release_readuids() {
  // @@protoc_insertion_point(field_release:com.chuzi.imsdk.server.model.proto.Message.readUIds)
  return readuids_.Release();
}
inline void Message::set_allocated_readuids(std::string* readuids) {
  if (readuids != nullptr) {
    
  } else {
    
  }
  readuids_.SetAllocated(readuids, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (readuids_.IsDefault()) {
    readuids_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:com.chuzi.imsdk.server.model.proto.Message.readUIds)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace model
}  // namespace server
}  // namespace imsdk
}  // namespace chuzi
}  // namespace com

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Message_2eproto
