// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SentBody.proto

#include "SentBody.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace com {
namespace chuzi {
namespace imsdk {
namespace server {
namespace model {
namespace proto {
PROTOBUF_CONSTEXPR SentBody_DataEntry_DoNotUse::SentBody_DataEntry_DoNotUse(
    ::_pbi::ConstantInitialized){}
struct SentBody_DataEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SentBody_DataEntry_DoNotUseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SentBody_DataEntry_DoNotUseDefaultTypeInternal() {}
  union {
    SentBody_DataEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SentBody_DataEntry_DoNotUseDefaultTypeInternal _SentBody_DataEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR SentBody::SentBody(
    ::_pbi::ConstantInitialized)
  : data_(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{})
  , key_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , timestamp_(int64_t{0}){}
struct SentBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SentBodyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SentBodyDefaultTypeInternal() {}
  union {
    SentBody _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SentBodyDefaultTypeInternal _SentBody_default_instance_;
}  // namespace proto
}  // namespace model
}  // namespace server
}  // namespace imsdk
}  // namespace chuzi
}  // namespace com
static ::_pb::Metadata file_level_metadata_SentBody_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_SentBody_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_SentBody_2eproto = nullptr;

const uint32_t TableStruct_SentBody_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::com::chuzi::imsdk::server::model::proto::SentBody_DataEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::com::chuzi::imsdk::server::model::proto::SentBody_DataEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::chuzi::imsdk::server::model::proto::SentBody_DataEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::com::chuzi::imsdk::server::model::proto::SentBody_DataEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::com::chuzi::imsdk::server::model::proto::SentBody, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::com::chuzi::imsdk::server::model::proto::SentBody, key_),
  PROTOBUF_FIELD_OFFSET(::com::chuzi::imsdk::server::model::proto::SentBody, timestamp_),
  PROTOBUF_FIELD_OFFSET(::com::chuzi::imsdk::server::model::proto::SentBody, data_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::com::chuzi::imsdk::server::model::proto::SentBody_DataEntry_DoNotUse)},
  { 10, -1, -1, sizeof(::com::chuzi::imsdk::server::model::proto::SentBody)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::com::chuzi::imsdk::server::model::proto::_SentBody_DataEntry_DoNotUse_default_instance_._instance,
  &::com::chuzi::imsdk::server::model::proto::_SentBody_default_instance_._instance,
};

const char descriptor_table_protodef_SentBody_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016SentBody.proto\022\"com.chuzi.imsdk.server"
  ".model.proto\"\235\001\n\010SentBody\022\013\n\003key\030\001 \001(\t\022\021"
  "\n\ttimestamp\030\002 \001(\003\022D\n\004data\030\003 \003(\01326.com.ch"
  "uzi.imsdk.server.model.proto.SentBody.Da"
  "taEntry\032+\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val"
  "ue\030\002 \001(\t:\0028\001B\017B\rSentBodyProtob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_SentBody_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_SentBody_2eproto = {
    false, false, 237, descriptor_table_protodef_SentBody_2eproto,
    "SentBody.proto",
    &descriptor_table_SentBody_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_SentBody_2eproto::offsets,
    file_level_metadata_SentBody_2eproto, file_level_enum_descriptors_SentBody_2eproto,
    file_level_service_descriptors_SentBody_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_SentBody_2eproto_getter() {
  return &descriptor_table_SentBody_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_SentBody_2eproto(&descriptor_table_SentBody_2eproto);
namespace com {
namespace chuzi {
namespace imsdk {
namespace server {
namespace model {
namespace proto {

// ===================================================================

SentBody_DataEntry_DoNotUse::SentBody_DataEntry_DoNotUse() {}
SentBody_DataEntry_DoNotUse::SentBody_DataEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void SentBody_DataEntry_DoNotUse::MergeFrom(const SentBody_DataEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata SentBody_DataEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SentBody_2eproto_getter, &descriptor_table_SentBody_2eproto_once,
      file_level_metadata_SentBody_2eproto[0]);
}

// ===================================================================

class SentBody::_Internal {
 public:
};

SentBody::SentBody(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  data_(arena) {
  SharedCtor();
  if (arena != nullptr && !is_message_owned) {
    arena->OwnCustomDestructor(this, &SentBody::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:com.chuzi.imsdk.server.model.proto.SentBody)
}
SentBody::SentBody(const SentBody& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  data_.MergeFrom(from.data_);
  key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_key().empty()) {
    key_.Set(from._internal_key(), 
      GetArenaForAllocation());
  }
  timestamp_ = from.timestamp_;
  // @@protoc_insertion_point(copy_constructor:com.chuzi.imsdk.server.model.proto.SentBody)
}

inline void SentBody::SharedCtor() {
key_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  key_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
timestamp_ = int64_t{0};
}

SentBody::~SentBody() {
  // @@protoc_insertion_point(destructor:com.chuzi.imsdk.server.model.proto.SentBody)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void SentBody::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  data_.Destruct();
  key_.Destroy();
}

void SentBody::ArenaDtor(void* object) {
  SentBody* _this = reinterpret_cast< SentBody* >(object);
  _this->data_.Destruct();
}
void SentBody::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SentBody::Clear() {
// @@protoc_insertion_point(message_clear_start:com.chuzi.imsdk.server.model.proto.SentBody)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  key_.ClearToEmpty();
  timestamp_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SentBody::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "com.chuzi.imsdk.server.model.proto.SentBody.key"));
        } else
          goto handle_unusual;
        continue;
      // int64 timestamp = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // map<string, string> data = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&data_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SentBody::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.chuzi.imsdk.server.model.proto.SentBody)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_key().data(), static_cast<int>(this->_internal_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "com.chuzi.imsdk.server.model.proto.SentBody.key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_key(), target);
  }

  // int64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_timestamp(), target);
  }

  // map<string, string> data = 3;
  if (!this->_internal_data().empty()) {
    using MapType = ::_pb::Map<std::string, std::string>;
    using WireHelper = SentBody_DataEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_data();
    auto check_utf8 = [](const MapType::value_type& entry) {
      (void)entry;
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.first.data(), static_cast<int>(entry.first.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "com.chuzi.imsdk.server.model.proto.SentBody.DataEntry.key");
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        entry.second.data(), static_cast<int>(entry.second.length()),
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
        "com.chuzi.imsdk.server.model.proto.SentBody.DataEntry.value");
    };

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterPtr<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
        check_utf8(entry);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:com.chuzi.imsdk.server.model.proto.SentBody)
  return target;
}

size_t SentBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.chuzi.imsdk.server.model.proto.SentBody)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> data = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_data_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_data().begin();
      it != this->_internal_data().end(); ++it) {
    total_size += SentBody_DataEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // string key = 1;
  if (!this->_internal_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  // int64 timestamp = 2;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SentBody::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    SentBody::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SentBody::GetClassData() const { return &_class_data_; }

void SentBody::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<SentBody *>(to)->MergeFrom(
      static_cast<const SentBody &>(from));
}


void SentBody::MergeFrom(const SentBody& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.chuzi.imsdk.server.model.proto.SentBody)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
  if (!from._internal_key().empty()) {
    _internal_set_key(from._internal_key());
  }
  if (from._internal_timestamp() != 0) {
    _internal_set_timestamp(from._internal_timestamp());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SentBody::CopyFrom(const SentBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.chuzi.imsdk.server.model.proto.SentBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SentBody::IsInitialized() const {
  return true;
}

void SentBody::InternalSwap(SentBody* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  data_.InternalSwap(&other->data_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &key_, lhs_arena,
      &other->key_, rhs_arena
  );
  swap(timestamp_, other->timestamp_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SentBody::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_SentBody_2eproto_getter, &descriptor_table_SentBody_2eproto_once,
      file_level_metadata_SentBody_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace model
}  // namespace server
}  // namespace imsdk
}  // namespace chuzi
}  // namespace com
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::com::chuzi::imsdk::server::model::proto::SentBody_DataEntry_DoNotUse*
Arena::CreateMaybeMessage< ::com::chuzi::imsdk::server::model::proto::SentBody_DataEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::chuzi::imsdk::server::model::proto::SentBody_DataEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::com::chuzi::imsdk::server::model::proto::SentBody*
Arena::CreateMaybeMessage< ::com::chuzi::imsdk::server::model::proto::SentBody >(Arena* arena) {
  return Arena::CreateMessageInternal< ::com::chuzi::imsdk::server::model::proto::SentBody >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
