pragma Singleton

import QtQuick 2.15

ListModel {

    ListElement{
        file:"emoji_00.png"
        name:"emoticon_emoji_0"
        tag:"[大笑]"
    }
    ListElement{
        file:"emoji_01.png"
        name:"emoticon_emoji_01"
        tag:"[开心]"
    }
    ListElement{
        file:"emoji_02.png"
        name:"emoticon_emoji_02"
        tag:"[色]"
    }
    ListElement{
        file:"emoji_03.png"
        name:"emoticon_emoji_03"
        tag:"[酷]"
    }
    ListElement{
        file:"emoji_04.png"
        name:"emoticon_emoji_04"
        tag:"[奸笑]"
    }
    ListElement{
        file:"emoji_05.png"
        name:"emoticon_emoji_05"
        tag:"[亲]"
    }
    ListElement{
        file:"emoji_06.png"
        name:"emoticon_emoji_06"
        tag:"[伸舌头]"
    }
    ListElement{
        file:"emoji_07.png"
        name:"emoticon_emoji_07"
        tag:"[眯眼]"
    }
    ListElement{
        file:"emoji_08.png"
        name:"emoticon_emoji_08"
        tag:"[可爱]"
    }
    ListElement{
        file:"emoji_09.png"
        name:"emoticon_emoji_09"
        tag:"[鬼脸]"
    }
    ListElement{
        file:"emoji_10.png"
        name:"emoticon_emoji_10"
        tag:"[偷笑]"
    }
    ListElement{
        file:"emoji_11.png"
        name:"emoticon_emoji_11"
        tag:"[喜悦]"
    }
    ListElement{
        file:"emoji_12.png"
        name:"emoticon_emoji_12"
        tag:"[狂喜]"
    }
    ListElement{
        file:"emoji_13.png"
        name:"emoticon_emoji_13"
        tag:"[惊讶]"
    }
    ListElement{
        file:"emoji_14.png"
        name:"emoticon_emoji_14"
        tag:"[流泪]"
    }
    ListElement{
        file:"emoji_15.png"
        name:"emoticon_emoji_15"
        tag:"[流汗]"
    }
    ListElement{
        file:"emoji_16.png"
        name:"emoticon_emoji_16"
        tag:"[天使]"
    }
    ListElement{
        file:"emoji_17.png"
        name:"emoticon_emoji_17"
        tag:"[笑哭]"
    }
    ListElement{
        file:"emoji_18.png"
        name:"emoticon_emoji_18"
        tag:"[尴尬]"
    }
    ListElement{
        file:"emoji_19.png"
        name:"emoticon_emoji_19"
        tag:"[惊恐]"
    }
    ListElement{
        file:"emoji_20.png"
        name:"emoticon_emoji_20"
        tag:"[大哭]"
    }
    ListElement{
        file:"emoji_21.png"
        name:"emoticon_emoji_21"
        tag:"[烦躁]"
    }
    ListElement{
        file:"emoji_22.png"
        name:"emoticon_emoji_22"
        tag:"[恐怖]"
    }
    ListElement{
        file:"emoji_23.png"
        name:"emoticon_emoji_23"
        tag:"[两眼冒星]"
    }
    ListElement{
        file:"emoji_24.png"
        name:"emoticon_emoji_24"
        tag:"[害羞]"
    }
    ListElement{
        file:"emoji_25.png"
        name:"emoticon_emoji_25"
        tag:"[睡着]"
    }
    ListElement{
        file:"emoji_26.png"
        name:"emoticon_emoji_26"
        tag:"[冒星]"
    }
    ListElement{
        file:"emoji_27.png"
        name:"emoticon_emoji_27"
        tag:"[口罩]"
    }
    ListElement{
        file:"emoji_28.png"
        name:"emoticon_emoji_28"
        tag:"[OK]"
    }
    ListElement{
        file:"emoji_29.png"
        name:"emoticon_emoji_29"
        tag:"[好吧]"
    }
    ListElement{
        file:"emoji_30.png"
        name:"emoticon_emoji_30"
        tag:"[鄙视]"
    }
    ListElement{
        file:"emoji_31.png"
        name:"emoticon_emoji_31"
        tag:"[难受]"
    }
    ListElement{
        file:"emoji_32.png"
        name:"emoticon_emoji_32"
        tag:"[不屑]"
    }
    ListElement{
        file:"emoji_33.png"
        name:"emoticon_emoji_33"
        tag:"[不舒服]"
    }
    ListElement{
        file:"emoji_34.png"
        name:"emoticon_emoji_34"
        tag:"[愤怒]"
    }
    ListElement{
        file:"emoji_35.png"
        name:"emoticon_emoji_35"
        tag:"[鬼怪]"
    }
    ListElement{
        file:"emoji_36.png"
        name:"emoticon_emoji_36"
        tag:"[发怒]"
    }
    ListElement{
        file:"emoji_37.png"
        name:"emoticon_emoji_37"
        tag:"[生气]"
    }
    ListElement{
        file:"emoji_38.png"
        name:"emoticon_emoji_38"
        tag:"[不高兴]"
    }
    ListElement{
        file:"emoji_39.png"
        name:"emoticon_emoji_39"
        tag:"[皱眉]"
    }
    ListElement{
        file:"emoji_40.png"
        name:"emoticon_emoji_40"
        tag:"[心碎]"
    }
    ListElement{
        file:"emoji_41.png"
        name:"emoticon_emoji_41"
        tag:"[心动]"
    }
    ListElement{
        file:"emoji_42.png"
        name:"emoticon_emoji_42"
        tag:"[好的]"
    }
    ListElement{
        file:"emoji_43.png"
        name:"emoticon_emoji_43"
        tag:"[低级]"
    }
    ListElement{
        file:"emoji_44.png"
        name:"emoticon_emoji_44"
        tag:"[赞]"
    }
    ListElement{
        file:"emoji_45.png"
        name:"emoticon_emoji_45"
        tag:"[鼓掌]"
    }
    ListElement{
        file:"emoji_46.png"
        name:"emoticon_emoji_46"
        tag:"[给力]"
    }
    ListElement{
        file:"emoji_47.png"
        name:"emoticon_emoji_47"
        tag:"[打你]"
    }
    ListElement{
        file:"emoji_48.png"
        name:"emoticon_emoji_48"
        tag:"[阿弥陀佛]"
    }
    ListElement{
        file:"emoji_49.png"
        name:"emoticon_emoji_49"
        tag:"[拜拜]"
    }
    ListElement{
        file:"emoji_50.png"
        name:"emoticon_emoji_50"
        tag:"[第一]"
    }
    ListElement{
        file:"emoji_51.png"
        name:"emoticon_emoji_51"
        tag:"[拳头]"
    }
    ListElement{
        file:"emoji_52.png"
        name:"emoticon_emoji_52"
        tag:"[手掌]"
    }
    ListElement{
        file:"emoji_53.png"
        name:"emoticon_emoji_53"
        tag:"[剪刀]"
    }
    ListElement{
        file:"emoji_54.png"
        name:"emoticon_emoji_54"
        tag:"[招手]"
    }
    ListElement{
        file:"emoji_55.png"
        name:"emoticon_emoji_55"
        tag:"[不要]"
    }
    ListElement{
        file:"emoji_56.png"
        name:"emoticon_emoji_56"
        tag:"[举着]"
    }
    ListElement{
        file:"emoji_57.png"
        name:"emoticon_emoji_57"
        tag:"[思考]"
    }
    ListElement{
        file:"emoji_58.png"
        name:"emoticon_emoji_58"
        tag:"[猪头]"
    }
    ListElement{
        file:"emoji_59.png"
        name:"emoticon_emoji_59"
        tag:"[不听]"
    }
    ListElement{
        file:"emoji_60.png"
        name:"emoticon_emoji_60"
        tag:"[不看]"
    }
    ListElement{
        file:"emoji_61.png"
        name:"emoticon_emoji_61"
        tag:"[不说]"
    }
    ListElement{
        file:"emoji_62.png"
        name:"emoticon_emoji_62"
        tag:"[猴子]"
    }
    ListElement{
        file:"emoji_63.png"
        name:"emoticon_emoji_63"
        tag:"[炸弹]"
    }
    ListElement{
        file:"emoji_64.png"
        name:"emoticon_emoji_64"
        tag:"[睡觉]"
    }
    ListElement{
        file:"emoji_65.png"
        name:"emoticon_emoji_65"
        tag:"[筋斗云]"
    }
    ListElement{
        file:"emoji_66.png"
        name:"emoticon_emoji_66"
        tag:"[火箭]"
    }
    ListElement{
        file:"emoji_67.png"
        name:"emoticon_emoji_67"
        tag:"[救护车]"
    }
    ListElement{
        file:"emoji_68.png"
        name:"emoticon_emoji_68"
        tag:"[便便]"
    }
}
